#Занятие 1. Вводное

##Введение (для тех, кто еще не понял, зачем он здесь)

В наше время, количество информации растет с невероятно большой скоростью. Человеку приходится работать с таким объемом данных, что уже на физическом уровне он не способен справиться с поставленной задачей. Поэтому машинное обучение все больше проникает в повседневную жизнь. <br>
Алгоритмы машинного обучения используются уже во многих сферах:<br>
•	В поисковых машинах доля поиска ответов на запрос;<br>
•	Для имитации личности (deep fake, lyrebird)<br>
•	В робототехнике (Boston dynamics)<br>
•	В рекомендательных системах и экспертных системах;<br>
•	В обеспечении безопасности (распознавание лиц и т.д.).<br>
Кроме того, есть информация, что благодаря нейронным сетям можно стать президентом США… (в 2012 году на время предвыборной кампании Барак Обама назначил Раида Гани, эксперта по машинному обучению, главным аналитиком) (если что, то победил Обама).<br>
Подводя итог, можно сказать, что нейронные сети откроют вам дорогу в светлое будущее. Они могут сделать невозможное возможным. Надо только захотеть.<br>


##Теоретическая часть

Здесь будет рассказано о том, что такое нейронные сети.<br><br>
Нейронные сети - это один из многих алгоритмов машинного обучения, позволяющий разделить данные на классы. Нейронная сеть выделяется среди этих алгоритмов тем, что её механизм получения результата схож с процессом работы нейронов в нашем мозге.<br>
![alt text](https://leonardo.osnova.io/9f49d911-e30d-f9af-5046-d608cf3e68be/-/scale_crop/520x241/center/) <br>
Рассмотрим модель биологического нейрона. В ней мы можем выделить несколько ос-новных частей: дендрит, аксон и синапс. Дендрит связан с внешним воздействием на нейрон. В аксоне выделяется межклеточное вещество. Количество этого вещества определя-ет, как среагирует синапс, связанный с дендритами других нейронов. Поэтому, видя какой-либо предмет, в нейронах человека каждый раз выделяется примерно одно и то же количе-ство межклеточного вещества. Примерно так устроена наша память и работа искусственного нейрона. Проведём аналогию с искусственными нейронами.<br>
![alt text](https://github.com/Lavabar/My-Neural-Networks-Course/raw/master/images/pic1.png)<br>
В простой модели искусственного нейрона (перцептроне) так же есть дендрит, аксон и синапс. На входной узел i поступают данные (то есть числа). Далее, они обрабатываются с помощью веса w. И выдают результат через выход o. Теперь о том, что значит «обрабатыва-ются» и что означает тот квадратик с надписью «Threshold». В первом случае находится сумма произведений пар значений (ik, wk), а во втором случае наша сумма проходит через активационную функцию. В данном случае в качестве активационной функции выступает Threshold, но существует еще и много других (самые распространенные sigmoid(S), tanh(S), softmax(S)).
<br>
Теперь нужно вспомнить, что в словосочетании «нейронная сеть» есть слово «сеть».
<br>
![alt text](https://habrastorage.org/getpro/habr/post_images/e61/3db/569/e613db56971c92a6dedae728ef6997e0.png)
<br>
Что мы здесь видим. Входными сигналами в данном случае считаются синие вершины графа (входной слой). Красными точками являются значения, полученные в результате работы активационной функции нашей нейронной сети (скрытый слой). Далее эти значения подаются в качестве входных для слоя зеленых точек (выходной слой), где они так же обрабатываются и подаются в активационную функцию. Результатом работы нейронной сети является набор выходных значений зеленых точек, каждую из которых можно интерпретировать как коэффициент принадлежности входных данных (значений синих точек) к одному из классов.
<br>
![alt text](https://github.com/Lavabar/My-Neural-Networks-Course/raw/master/images/pic2.jpg)
<br>
Теперь нужно поговорить о самом главном. Откуда нам брать значения для весов w. Ответ на этот вопрос лежит в понятии «обучения» нейронной сети. Обучение нейронной сети – это «подстройка» весов сети таким образом, чтобы она выдавала необходимый результат на определенные входные данные. Все происходит так.<br> 
Вы создали нейронную сеть. Задали количество слоев, количество нейронов на каждом слое, выбрали функции активации. После этого всего в вашей сети происходит инициализация весов на каждом слое. Веса задаются случайным образом, так как в таком случае больше вероятность попасть сразу в цель.<br>
Перед тем, как начать обучение нейронной сети, вы должны где-то найти обучающую выборку для нее (обучающая выборка – это когда у вас есть множество наборов входных данных и соответствующие им выходные данные). После этого берете первый набор входных данных и прогоняете через нейронную сеть. Теперь у вас есть выходные значения, которые дала сеть и выходные значения, которые вы от нее ждали. На основе разницы этих значений корректируются значения весов сети. Все происходит с помощью метода обратного распространения ошибки. Грубо говоря, в этом методе мы считаем «ошибку» для каждого нейрона, далее проходим по каждому весу сети и считаем для него значение оптимизационной функции (среди них могут быть sgd, adam, rmsprop) и это значение прибавляем к текущему значению веса. В итоге мы получаем нейронную сеть с новыми, более подходящими для нашей задачи весами. Важно отметить, что функция оптимизации дает лишь корректировочное значение для определенного веса, но никак не конечные значения. То есть, чтобы обучить нейронную сеть необходимо применить метод обратного распространения ошибки (backpropagation) несколько раз (много).


##Практическая часть

Теперь попробуем подкрепить практику теорией.<br>
(Чтобы не заморачиваться с установкой всяких библиотек и не засорять свой комп, советую воспользоваться google colaboratory https://colab.research.google.com . Разобраться очень просто, почекайте examples)<br>
Для того, чтобы продолжить дальше, вам необходимо установить numpy, tensorflow и keras (лучше это сделать именно в таком порядке) при помощи pip.


In [0]:
!pip install numpy
!pip install tensorflow
!pip install keras

Во время установки соглашайтесь на установление всех зависимостей. <br>
Теперь остановимся подробнее на numpy, а дальше перейдем сразу к нейронкам.<br>
###Интенсив по numpy
NumPy — это библиотека языка Python, добавляющая поддержку больших многомерных массивов и матриц, вместе с большой библиотекой высокоуровневых (и очень быстрых) математических функций для операций с этими массивами. Это очень мощный инструмент для работы с вашими данными, старайтесь использовать его, как можно чаще.<br>
Основным объектом NumPy является однородный многомерный массив (в numpy называется numpy.ndarray). Это многомерный массив элементов (обычно чисел), одного типа.<br>
Наиболее важные атрибуты объектов ndarray:<br>
•	ndarray.shape - размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). Число элементов кортежа shape равно ndim.<br>
•	ndarray.size - количество элементов массива. Очевидно, равно произведению всех элементов атрибута shape.<br>
•	ndarray.dtype - объект, описывающий тип элементов массива.<br>
<br>
В NumPy существует много способов создать массив. Один из наиболее простых - создать массив из обычных списков или кортежей Python, используя функцию numpy.array() (запомните: array - функция, создающая объект типа ndarray):
<br>

In [0]:
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [0]:
b = np.array([[1.5, 2, 3], [4, 5, 6]])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

Функция zeros() создает массив из нулей, а функция ones() — массив из единиц. Обе функции принимают кортеж с размерами, и аргумент dtype:

In [0]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Для создания последовательностей чисел, в NumPy имеется функция arange(), аналогичная встроенной в Python range(), только вместо списков она возвращает массивы, и принимает не только целые значения:

In [0]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [0]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

На этом пока остановимся. Теперь перейдем к самому интересному. Для начала попробуем написать нейронную сеть, которая бы распознавала рукописные цифры.

###Создаем нейронную сеть на keras

В keras уже есть некоторые датасеты, поэтому мы пока просто воспользуемся одним из них, чтобы не терять время. 
Импортируем из кераса датасет с рукописными цифрами mnist и сразу же загрузим его.
В X_train и X_test у нас будут лежать картинки, а в Y_train и Y_test ответы. 

In [0]:
from keras.datasets import mnist

(X_train, Y_train), (X_test, Y_test) = mnist.load_data()

Using TensorFlow backend.


11493376/11490434 [==============================] - 0s 0us/step


Теперь посмотрим, что у нас скачалось и в каком виде представлены данные. Перед этим обратите внимание на тип данных скачанного датасета

In [0]:
print(type(X_train))

<class 'numpy.ndarray'>


Keras и многие другие фреймворки использует numpy.ndarray в качестве основного типа данных. Поэтому воспользуемся нашими знаниями по numpy и распечатаем shape наших данных

In [0]:
print(X_train.shape)
print(Y_train.shape)

print(X_test.shape)
print(Y_test.shape)

(60000, 28, 28)
(60000,)
(10000, 28, 28)
(10000,)


Получается, что у нас входные данные представлены в виде массива матриц 28х28 (то есть это просто картинка в привычном нам виде), а выходные в виде массива цифр. Мы же, в нашей сети будем эти данные использовать в ином виде. Нам нужно чтобы входные данные были представлены не в виде последовательности матриц, а в виде последовательности одномерных массивов. То  есть нам нужно вытянуть наши картинки в 1 ряд. Выходные же данные надо представить в т.н hot-vector виде. Это когда:
0 = (1, 0, 0, 0, 0, 0, 0, 0, 0, 0)
1 = (0, 1, 0, 0, 0, 0, 0, 0, 0, 0)
2 = (0, 0, 1, 0, 0, 0, 0, 0, 0, 0)
и т.д
Для входных данных воспользуемся методом reshape, а для выходных данных надо будет импортировать из keras утилиту to_categorical.

In [0]:
X_train = X_train.reshape(60000, 784) # 28*28 == 784
X_test = X_test.reshape(10000, 784)

from keras.utils import to_categorical

Y_train = to_categorical(Y_train, 10) # 10 - количество цифр
Y_test = to_categorical(Y_test, 10)

print(X_train.shape)
print(Y_train.shape)

print(X_test.shape)
print(Y_test.shape)

(60000, 784)
(60000, 10)
(10000, 784)
(10000, 10)


Отлично! Теперь подробнее рассмотрим входные данные

In [0]:
print(X_train[0])

[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   0   0   0   0   0   0   0   0   3  18  18  18 126 136 175  26 166 255
 247 127   0   0   0   0   0   0   0   0   0   0   0   0  30  36  94 154
 170 253 253 253 253 253 225 172 253 242 195  64   0   0   0   0   0   0
   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251  93  82
  82  56  39   0   0   0   0   0   0   0   0   0   0   0   0  18 219 253
 253 253 253 253 198 182 247 241   0   0   0   0   

Как вы можете заметить, у нас тут числа от 0 до 255, но так не пойдет. Нейронные сети работают с нормализованными данными. Это обусловнено тем, что на вход могут подаваться данные совершенно разного типа и характера. Например, часть значений может быть от 0 до 255, а другая часть значений от 4 до 36,5. И если оставить значения в таком виде, то нейросеть будет вопринимать максимальное значение 36,5 как не очень большое, потому что есть еще 255. Но и 36,5 и 255 должны иметь одинаковую силу. Поэтому мы сейчас нормализуем наши входные данные (то есть приведем их к виду [0, 1]). Для этого преобразуем целые числа в вещественные и поделим все значения на максимально возможное

In [0]:
X_train = X_train.astype('float32')
X_test = X_test.astype('float32')

X_train /= 255
X_test /= 255

print(X_train[0])

[0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         

Замечательно! Ну теперь точно все, начинаем..

Сначала импортируем все, что нам нужно для создания и обучения модели искусственной нейронной сети.<br>
В Керасе есть два вида моделей. Это Sequential и  Model. Sequential это модель, где слои соединены последовательно, один за другим (то есть один входной слой и один выходной). Model - это базовый класс Sequential, то есть используя его, вы получаете некоторую свободу действий и можете проявить свою творческую натуру. <br>
Что касается Dense, то это класс слоя, который называется полносвязным (то есть у него все входы связаны со всеми выходами предыдущего слоя и все выходы связаны со всеми входами следующего)

In [0]:
from keras.models import Sequential
from keras.layers import Dense

Создадим нейросеть
<br>
![alt text](https://habrastorage.org/getpro/habr/post_images/e61/3db/569/e613db56971c92a6dedae728ef6997e0.png)
<br>
Получится она у нас примерно вот такого вида. Только у нас будет 784 синих вершин, 800 красных и 10 зеленых :) <br>
Первый полносвязный слой у нас вышел с 784 входами и 800 нейронами, каждый из которых будет активироваться функцией relu
Второй с 800 входами и 10 выходами и функцией softmax
<br>
Скомпилируем модель, добавляя в нее следующие свойства:<br>
Функция подсчета ошибки - categorical_crossentropy<br>
Функция оптимизации весов - adam<br>
Показатель работы нейронной сети - accuracy (то есть количество правильно распознанных данных на количество всех)
<br><br>(Если вам будет очень интересно, то попробуйте поподставлять другие методы loss и optimization из документации кераса и посмотрите, как будет меняться результат)

In [0]:
model = Sequential()
model.add(Dense(800, input_dim=784, activation='relu'))
model.add(Dense(10, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['accuracy'])

print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 800)               628000    
_________________________________________________________________
dense_2 (Dense)              (None, 10)                8010      
Total params: 636,010
Trainable params: 636,010
Non-trainable params: 0
_________________________________________________________________
None


Прежде чем начинать обучение поговорим о стратегиях обучения...<br>
Обучение можно производить тремя методами: стохастический метод (stochastic), пакетный метод (batch) и мини-пакетный метод (mini-batch). Существует очень много статей и исследований на тему того, какой из методов лучше и никто не может прийти к общему ответу.

Вкратце о каждом методе:

Стохастический (его еще иногда называют онлайн) метод работает по следующему принципу — нашел Δw, сразу обнови соответствующий вес.

Пакетный метод же работает по другому. Мы суммируем Δw всех весов на текущей итерации и только потом обновляем все веса используя эту сумму. Один из самых важных плюсов такого подхода — это значительная экономия времени на вычисление, точность же в таком случае может сильно пострадать.

Мини-пакетный метод является золотой серединой и пытается совместить в себе плюсы обоих методов. Здесь принцип таков: мы в свободном порядке распределяем веса по группам и меняем их веса на сумму Δw всех весов в той или иной группе.
<br>
За обучение нейронки в керасе отвечает метод fit. В качестве параметров он принимает входные данные, выходные данные, размер мини-пакета (1, если стохастический и 60000, если пакетный), количество итераций обучения нейронной сети (1 итерация - это прого всех примеров из обучающей выборки), процент данных выборки, который пойдет на валидацию (то есть на предварительную оценку качества обучения)

Мы в данном случае применим мини-пакетный метод обучения и будем менять веса после каждых 200 изображений.
<br>
Прогоним все изображения 25 раз подряд
<br>
На валидацию будет уходить 20% избражений
<br>
<br>
verbose - это режим вывода логов

In [0]:
history = model.fit(X_train, Y_train, batch_size=200, epochs=25, validation_split=0.2, verbose=2)

Train on 48000 samples, validate on 12000 samples
Epoch 1/25
 - 5s - loss: 1.9070e-05 - acc: 1.0000 - val_loss: 0.0945 - val_acc: 0.9836
Epoch 2/25
 - 5s - loss: 1.6436e-05 - acc: 1.0000 - val_loss: 0.0954 - val_acc: 0.9828
Epoch 3/25
 - 5s - loss: 1.4608e-05 - acc: 1.0000 - val_loss: 0.0959 - val_acc: 0.9833
Epoch 4/25
 - 5s - loss: 1.2818e-05 - acc: 1.0000 - val_loss: 0.0968 - val_acc: 0.9830
Epoch 5/25
 - 5s - loss: 1.1419e-05 - acc: 1.0000 - val_loss: 0.0973 - val_acc: 0.9834
Epoch 6/25
 - 5s - loss: 1.0229e-05 - acc: 1.0000 - val_loss: 0.0965 - val_acc: 0.9836
Epoch 7/25
 - 5s - loss: 8.9668e-06 - acc: 1.0000 - val_loss: 0.0982 - val_acc: 0.9833
Epoch 8/25
 - 5s - loss: 7.8521e-06 - acc: 1.0000 - val_loss: 0.0988 - val_acc: 0.9830
Epoch 9/25
 - 5s - loss: 7.1381e-06 - acc: 1.0000 - val_loss: 0.0987 - val_acc: 0.9835
Epoch 10/25
 - 5s - loss: 6.3087e-06 - acc: 1.0000 - val_loss: 0.0995 - val_acc: 0.9833
Epoch 11/25
 - 5s - loss: 5.5889e-06 - acc: 1.0000 - val_loss: 0.1007 - val_acc

Ура! Теперь, после небольшого ожидания проверим, как нейронная сеть обучилась. Для этого воспользуемся тестовыми данными.

In [0]:
scores = model.evaluate(X_test, Y_test, verbose=0)
print("Точность работы на тестовых данных: %.2f%%" % (scores[1]*100))

Точность работы на тестовых данных: 98.23%


Получается, что наша сеть смогла правильно распознать почти все тестовые примеры (заметьте, что раньше она эти данные не видела)

In [0]:
import numpy as np

exmpl = 432 # попробуем получить результат из 432 изображения
x = X_test[exmpl]
x = np.expand_dims(x, axis=0)

Более наглядно показано, что мы только что сделали...

In [0]:
### Просто пример
abc = np.array([1, 2, 3])

bcd = np.expand_dims(abc, axis=0)

abc = np.asarray([abc])

print(abc.shape)
print(bcd.shape)
###

(1, 3)
(1, 3)


И напоследок зафигачим предикшон

In [0]:
predict = model.predict(x)
print(predict)
number = np.argmax(predict)
print(number)

[[1.2222338e-14 7.6561896e-08 3.1316326e-06 1.0312326e-06 9.9895132e-01
  1.0369174e-03 6.4486403e-06 4.2626263e-07 3.7438950e-09 6.5984528e-07]]
4


Вот и все, в принципе)

##Если у вас еще остались вопросы

https://habr.com/post/369349/ (забавное объяснение нейронных сетей, которое поможет глубже погрузиться в тему)<br>
https://pythonworld.ru/numpy/1.html (туториал по numpy)<br>
https://habr.com/post/352678/ (другой туториал по numpy)<br>
[Подробнее о функциях активации можно найти здесь](https://edu.kpfu.ru/pluginfile.php/288277/mod_wiki/attachments/158/%D0%9D%D0%B0%D0%B3%D0%BC%D0%B0%D1%82%D1%83%D0%BB%D0%BB%D0%B8%D0%BD_%D0%A2%D0%B8%D0%BC%D1%83%D1%80_%D0%9E%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5 %D0%BD%D0%B5%D0%B9%D1%80%D0%BE%D0%BD%D0%BD%D0%BE%D0%B9 %D1%81%D0%B5%D1%82%D0%B8. %D0%A4%D1%83%D0%BD%D0%BA%D1%86%D0%B8%D1%8F %D0%B0%D0%BA%D1%82%D0%B8%D0%B2%D0%B0%D1%86%D0%B8%D0%B8 %D0%BD%D0%B5%D0%B9%D1%80%D0%BE%D0%BD%D0%BD%D0%BE%D0%B9 %D1%81%D0%B5%D1%82%D0%B8..docx?forcedownload=1)<br>
https://www.asozykin.ru/courses/nnpython (крутой дядька, который рассказывает, как писать нейросети на keras)<br>
https://www.youtube.com/channel/UCWN3xxRkmTPmbKwht9FuE5A (тоже крутой дядька, но английском)<br>
Если у вас совсем все плохо или вы нашли несоответствие с действительностью, то можно написать в телеге (@lavabar) или по почте (lavabarser@gmail.com)


##Документация

https://devdocs.io/numpy/ <br>
https://keras.io/

##Внеклассное чтение

https://habr.com/post/271563/ (тут на Питоне написана очень простая нейронка без фреймворков)<br>
https://habr.com/post/272679/ (придет лучшее понимание методов оптимизации весов, объяснение на интуитивных примерах) <br>
https://habr.com/post/198268/ (хорошая статья про обучение нейронных сетей)<br>
https://habr.com/post/307004/ (больше математики)


##Домашнее задание

Необходимо написать нейронную сеть для анализа тональности текста на основе всего того, что мы сегодня прошли. 
<br>
Смысл: Вы вводите в бота сообщение: "Какой замечательный день", а бот выводит: "Хорошо/плохо на 76%"<br>
<br>
Рекомендации:<br>
https://www.kaggle.com/c/sentiment-analysis-in-russian - датасет(https://stackoverflow.com/questions/20199126/reading-json-from-a-file)<br>
Необходимо будет изучить keras.preprocessing.text.Tokenizer и keras.preprocessing.sequence.pad_sequences<br>
Также изучите работу слоя Embedding в keras<br>
Все это вам очень пригодится для представления слов в виде, удобном для нейронки.

In [0]:
### Примерный вариант использования Tokenizer и pad_sequences
import numpy as np
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

text_base = np.array(['егор пошел домой', 'ему очень сильно нравятся нейронные сети', 'предложение со случайными словами'])

max_fatures = 15
#max_fatures = 10 
# Обратите внимание на то, что если max_fatures сделать слишком маленьким,
# то тогда вы можете потерять информацию. Оценивайте количество возможных слов правильно

tokenizer = Tokenizer(num_words=max_fatures, split=' ')
tokenizer.fit_on_texts(text_base)
X = tokenizer.texts_to_sequences(text_base)
X = pad_sequences(X)
print(X)
# Дальше все это дело подается на вход слоя Embedding

[[ 0  0  0  1  2  3]
 [ 4  5  6  7  8  9]
 [ 0  0 10 11 12 13]]
